/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sewalapangan;

import java.awt.HeadlessException;
import java.sql.SQLException;

/**
 *
 * @author Elle
 */
  

    public final class MainFrame extends javax.swing.JFrame {

        /**
         * Creates new form MainFrame
         */
        public MainFrame() {
            initComponents();
            tampilDataLapangan();
            tampilDataPelanggan();
            tampilDataTransaksi(); 
            muatPilihanPelanggan(); 
            muatPilihanLapangan();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNoNota = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLapangan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdLapangan = new javax.swing.JTextField();
        txtNamaLapangan = new javax.swing.JTextField();
        txtHargaLapangan = new javax.swing.JTextField();
        cbJenisLapangan = new javax.swing.JComboBox<>();
        btnSimpanLapangan = new javax.swing.JButton();
        btnEditLapangan = new javax.swing.JButton();
        btnHapusLapangan = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPelanggan = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIdPelanggan = new javax.swing.JTextField();
        txtNamaPelanggan = new javax.swing.JTextField();
        txtNoTelp = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        btnSimpanPelanggan = new javax.swing.JButton();
        btnEditPelanggan = new javax.swing.JButton();
        btnHapusPelanggan = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNotaBooking = new javax.swing.JTextField();
        cbIdPelanggan = new javax.swing.JComboBox<>();
        cbIdLapangan = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtHargaSewa = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtLamaSewa = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTotalBayar = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        btnSimpanTransaksi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblLapangan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLapangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLapanganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLapangan);

        jLabel1.setText("ID LAPANGAN");

        jLabel2.setText("NAMA LAPANGAN");

        jLabel3.setText("JENIS LAPANGAN");

        jLabel4.setText("HARGA PER JAM");

        txtHargaLapangan.addActionListener(this::txtHargaLapanganActionPerformed);

        cbJenisLapangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SYNTETIS", "VINYL", "MATRAS" }));

        btnSimpanLapangan.setText("SIMPAN");
        btnSimpanLapangan.addActionListener(this::btnSimpanLapanganActionPerformed);

        btnEditLapangan.setText("EDIT");
        btnEditLapangan.addActionListener(this::btnEditLapanganActionPerformed);

        btnHapusLapangan.setText("HAPUS");
        btnHapusLapangan.addActionListener(this::btnHapusLapanganActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbJenisLapangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHargaLapangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNamaLapangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdLapangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSimpanLapangan)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditLapangan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapusLapangan)))
                .addContainerGap(259, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtIdLapangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNamaLapangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbJenisLapangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtHargaLapangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpanLapangan)
                            .addComponent(btnEditLapangan)
                            .addComponent(btnHapusLapangan)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtNoNota.addTab("Data Lapangan", jPanel1);

        tblPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPelangganMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPelanggan);

        jLabel5.setText("ID PELANGGAN");

        jLabel6.setText("NAMA PELANGGAN");

        jLabel7.setText("NO. TELP");

        jLabel8.setText("ALAMAT");

        txtIdPelanggan.addActionListener(this::txtIdPelangganActionPerformed);

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane3.setViewportView(txtAlamat);

        btnSimpanPelanggan.setText("SIMPAN");
        btnSimpanPelanggan.addActionListener(this::btnSimpanPelangganActionPerformed);

        btnEditPelanggan.setText("EDIT");
        btnEditPelanggan.addActionListener(this::btnEditPelangganActionPerformed);

        btnHapusPelanggan.setText("HAPUS");
        btnHapusPelanggan.addActionListener(this::btnHapusPelangganActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSimpanPelanggan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditPelanggan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapusPelanggan))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIdPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtIdPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanPelanggan)
                    .addComponent(btnEditPelanggan)
                    .addComponent(btnHapusPelanggan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtNoNota.addTab("Data Pelanggan\n", jPanel2);

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tblTransaksi);

        jLabel9.setText("NO NOTA");

        jLabel10.setText("ID PELANGGAN");

        jLabel11.setText("ID LAPANGAN");

        txtNotaBooking.addActionListener(this::txtNotaBookingActionPerformed);

        cbIdPelanggan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbIdLapangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbIdLapangan.addActionListener(this::cbIdLapanganActionPerformed);

        jLabel12.setText("HARGA/JAM");

        txtHargaSewa.setEditable(false);

        jLabel13.setText("LAMA SEWA (JAM)");

        jLabel14.setText("TOTAL BAYAR");

        txtTotalBayar.setEditable(false);

        btnHitung.setText("HITUNG");
        btnHitung.addActionListener(this::btnHitungActionPerformed);

        btnSimpanTransaksi.setText("SIMPAN");
        btnSimpanTransaksi.addActionListener(this::btnSimpanTransaksiActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txtNotaBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbIdPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnHitung)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLamaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHargaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbIdLapangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSimpanTransaksi))))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtNotaBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cbIdPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cbIdLapangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtHargaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtLamaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHitung)
                            .addComponent(btnSimpanTransaksi))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtNoNota.addTab("Transaksi Booking", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNoNota)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtNoNota)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHargaLapanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaLapanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaLapanganActionPerformed

    private void btnEditLapanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditLapanganActionPerformed
    try {
        String id = txtIdLapangan.getText();
        String nama = txtNamaLapangan.getText();
        String jenis = cbJenisLapangan.getSelectedItem().toString();
        String harga = txtHargaLapangan.getText();

        if (id.equals("") || nama.equals("") || harga.equals("")) {
            javax.swing.JOptionPane.showMessageDialog(null, "Pilih data pada tabel terlebih dahulu dan pastikan semua field diisi!");
        } else {
            String sql = "UPDATE lapangan SET nama_lapangan=?, jenis_lapangan=?, harga_perjam=? WHERE id_lapangan=?";
            java.sql.Connection conn = Koneksi.koneksiDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, nama);
            pst.setString(2, jenis);
            pst.setString(3, harga);
            pst.setString(4, id);
            pst.execute();

            javax.swing.JOptionPane.showMessageDialog(null, "Data Lapangan Berhasil Diubah!");

            // Reset Form Lapangan agar siap dipakai input baru lagi
            txtIdLapangan.setText("");
            txtIdLapangan.setEditable(true);
            txtNamaLapangan.setText("");
            cbJenisLapangan.setSelectedIndex(0);
            txtHargaLapangan.setText("");
            tampilDataLapangan(); // Refresh tabel visual
        }
    } catch (java.awt.HeadlessException | java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Gagal mengubah data: " + e.getMessage());
    } // TODO add your handling code here:
    }//GEN-LAST:event_btnEditLapanganActionPerformed

    private void btnSimpanLapanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanLapanganActionPerformed
        try {
            String id = txtIdLapangan.getText();
            String nama = txtNamaLapangan.getText();
            String jenis = cbJenisLapangan.getSelectedItem().toString();
            String harga = txtHargaLapangan.getText();

            // Validasi agar user tidak mengosongkan inputan
            if (id.equals("") || nama.equals("") || harga.equals("")) {
                javax.swing.JOptionPane.showMessageDialog(this, "Semua data lapangan wajib diisi!");
            } else {
                // Query SQL untuk memasukkan data ke tabel lapangan
                String sql = "INSERT INTO lapangan (id_lapangan, nama_lapangan, jenis_lapangan, harga_perjam) VALUES (?, ?, ?, ?)";
                java.sql.Connection conn = Koneksi.koneksiDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);

                pst.setString(1, id);
                pst.setString(2, nama);
                pst.setString(3, jenis);
                pst.setString(4, harga);
                pst.executeUpdate();
                muatPilihanLapangan();

                javax.swing.JOptionPane.showMessageDialog(null, "Data Lapangan Berhasil Disimpan!");

                // Membersihkan kembali semua kotak inputan setelah sukses disimpan
                txtIdLapangan.setText("");
                txtNamaLapangan.setText("");
                cbJenisLapangan.setSelectedIndex(0);
                txtHargaLapangan.setText("");
                tampilDataLapangan();
            }
        } catch (HeadlessException | SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanLapanganActionPerformed

    private void btnSimpanPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanPelangganActionPerformed

        try {
            String id = txtIdPelanggan.getText();
            String nama = txtNamaPelanggan.getText();
            String telp = txtNoTelp.getText();
            String alamat = txtAlamat.getText();

            if (id.equals("") || nama.equals("") || telp.equals("") || alamat.equals("")) {
                javax.swing.JOptionPane.showMessageDialog(this, "Semua data pelanggan wajib diisi!");
            } else {
                String sql = "INSERT INTO pelanggan (id_pelanggan, nama_pelanggan, no_telp, alamat) VALUES (?, ?, ?, ?)";
                java.sql.Connection conn = Koneksi.koneksiDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);

                pst.setString(1, id);
                pst.setString(2, nama);
                pst.setString(3, telp);
                pst.setString(4, alamat);
                pst.executeUpdate();
                muatPilihanPelanggan();

                javax.swing.JOptionPane.showMessageDialog(null, "Data Pelanggan Berhasil Disimpan!");

                txtIdPelanggan.setText("");
                txtNamaPelanggan.setText("");
                txtNoTelp.setText("");
                txtAlamat.setText("");
                tampilDataPelanggan();
            }
        } catch (HeadlessException | SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan data pelanggan: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanPelangganActionPerformed

    private void txtIdPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPelangganActionPerformed

    private void tblPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPelangganMouseClicked
            int baris = tblPelanggan.rowAtPoint(evt.getPoint());

            String id = tblPelanggan.getValueAt(baris, 0).toString();
            txtIdPelanggan.setText(id);
            // ID dijadikan Primary Key, jadi kita matikan fungsinya agar tidak bisa diedit saat mode EDIT
            txtIdPelanggan.setEditable(false);

            String nama = tblPelanggan.getValueAt(baris, 1).toString();
            txtNamaPelanggan.setText(nama);

            String telp = tblPelanggan.getValueAt(baris, 2).toString();
            txtNoTelp.setText(telp);

            String alamat = tblPelanggan.getValueAt(baris, 3).toString();
            txtAlamat.setText(alamat);
    }//GEN-LAST:event_tblPelangganMouseClicked

    private void tblLapanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLapanganMouseClicked
        int baris = tblLapangan.rowAtPoint(evt.getPoint());

        String id = tblLapangan.getValueAt(baris, 0).toString();
        txtIdLapangan.setText(id);
        // Kita matikan fungsinya agar ID Lapangan tidak bisa diotak-atik saat mode EDIT
        txtIdLapangan.setEditable(false);

        String nama = tblLapangan.getValueAt(baris, 1).toString();
        txtNamaLapangan.setText(nama);

        // Untuk ComboBox Jenis Lapangan, kita set item yang terpilih sesuai data dari tabel
        String jenis = tblLapangan.getValueAt(baris, 2).toString();
        cbJenisLapangan.setSelectedItem(jenis);

        String harga = tblLapangan.getValueAt(baris, 3).toString();
        txtHargaLapangan.setText(harga);
        // TODO add your handling code here:
    }//GEN-LAST:event_tblLapanganMouseClicked

    private void btnEditPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPelangganActionPerformed
        try {
            String id = txtIdPelanggan.getText();
            String nama = txtNamaPelanggan.getText();
            String telp = txtNoTelp.getText();
            String alamat = txtAlamat.getText();

            if (id.equals("") || nama.equals("") || telp.equals("") || alamat.equals("")) {
                javax.swing.JOptionPane.showMessageDialog(null, "Pilih data pada tabel terlebih dahulu dan pastikan semua field diisi!");
            } else {
                String sql = "UPDATE pelanggan SET nama_pelanggan=?, no_telp=?, alamat=? WHERE id_pelanggan=?";
                java.sql.Connection conn = Koneksi.koneksiDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);

                pst.setString(1, nama);
                pst.setString(2, telp);
                pst.setString(3, alamat);
                pst.setString(4, id);
                pst.execute();

                javax.swing.JOptionPane.showMessageDialog(null, "Data Pelanggan Berhasil Diubah!");

                // Reset Form Pelanggan
                txtIdPelanggan.setText("");
                txtIdPelanggan.setEditable(true);
                txtNamaPelanggan.setText("");
                txtNoTelp.setText("");
                txtAlamat.setText("");
                tampilDataPelanggan();
            }
        } catch (java.awt.HeadlessException | java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Gagal mengubah data: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEditPelangganActionPerformed

    private void btnHapusLapanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusLapanganActionPerformed
// Untuk btnHapusLapanganActionPerformed
try {
    String id = txtIdLapangan.getText();
    if (id.equals("")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus dari tabel terlebih dahulu!");
    } else {
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data lapangan ini?", "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            String sql = "DELETE FROM lapangan WHERE id_lapangan=?";
            java.sql.Connection conn = Koneksi.koneksiDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, id);
            pst.execute();
            
            javax.swing.JOptionPane.showMessageDialog(this, "Data Lapangan Berhasil Dihapus!");
            
            // Reset Form
            txtIdLapangan.setText("");
            txtIdLapangan.setEditable(true);
            txtNamaLapangan.setText("");
            cbJenisLapangan.setSelectedIndex(0);
            txtHargaLapangan.setText("");
            tampilDataLapangan();
        }
    }
} catch (java.sql.SQLException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusLapanganActionPerformed

    private void btnHapusPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusPelangganActionPerformed
// Untuk btnHapusPelangganActionPerformed
try {
    String id = txtIdPelanggan.getText();
    if (id.equals("")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih data pelanggan yang ingin dihapus dari tabel terlebih dahulu!");
    } else {
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data pelanggan ini?", "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            String sql = "DELETE FROM pelanggan WHERE id_pelanggan=?";
            java.sql.Connection conn = Koneksi.koneksiDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, id);
            pst.execute();
            
            javax.swing.JOptionPane.showMessageDialog(this, "Data Pelanggan Berhasil Dihapus!");
            
            // Reset Form
            txtIdPelanggan.setText("");
            txtIdPelanggan.setEditable(true);
            txtNamaPelanggan.setText("");
            txtNoTelp.setText("");
            txtAlamat.setText("");
            tampilDataPelanggan();
        }
    }
} catch (java.sql.SQLException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus data pelanggan: " + e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusPelangganActionPerformed

    private void txtNotaBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNotaBookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNotaBookingActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
try {
    // Mengambil angka dari txtHargaSewa dan txtLamaSewa
    int harga = Integer.parseInt(txtHargaSewa.getText());
    int lamaSewa = Integer.parseInt(txtLamaSewa.getText());
    
    // Melakukan perkalian
    int total = harga * lamaSewa;
    
    // Menampilkan hasil perkalian ke txtTotalBayar
    txtTotalBayar.setText(String.valueOf(total));
} catch (NumberFormatException e) {
    javax.swing.JOptionPane.showMessageDialog(null, "Pastikan Lama Sewa sudah diisi dengan angka!");
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnHitungActionPerformed

    private void cbIdLapanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIdLapanganActionPerformed
if (cbIdLapangan.getSelectedIndex() > 0) {
    try {
        java.sql.Connection conn = Koneksi.koneksiDB();
        String sql = "SELECT harga_perjam FROM lapangan WHERE id_lapangan=?";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, cbIdLapangan.getSelectedItem().toString());
        java.sql.ResultSet rs = pst.executeQuery();
        
        if (rs.next()) {
            txtHargaSewa.setText(rs.getString("harga_perjam"));
        }
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Gagal mengambil harga: " + e.getMessage());
    }
} else {
    txtHargaSewa.setText("");
}        // TODO add your handling code here:
    }//GEN-LAST:event_cbIdLapanganActionPerformed

    private void btnSimpanTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanTransaksiActionPerformed
// Validasi apakah ada data yang belum diisi atau dipilih
if (txtNotaBooking.getText().equals("") || 
    cbIdPelanggan.getSelectedIndex() == 0 || 
    cbIdLapangan.getSelectedIndex() == 0 || 
    txtLamaSewa.getText().equals("") || 
    txtTotalBayar.getText().equals("")) {
    
    javax.swing.JOptionPane.showMessageDialog(null, "Mohon lengkapi semua data dan klik HITUNG terlebih dahulu!");
} else {
    try {
        java.sql.Connection conn = Koneksi.koneksiDB();
        String sql = "INSERT INTO transaksi (no_nota, id_pelanggan, id_lapangan, lama_sewa, total_bayar) VALUES (?, ?, ?, ?, ?)";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        
        // Memasukkan data ke query SQL (txtNotaBooking sesuai dengan nama variabel barumu)
        pst.setString(1, txtNotaBooking.getText());
        pst.setString(2, cbIdPelanggan.getSelectedItem().toString());
        pst.setString(3, cbIdLapangan.getSelectedItem().toString());
        pst.setInt(4, Integer.parseInt(txtLamaSewa.getText()));
        pst.setInt(5, Integer.parseInt(txtTotalBayar.getText()));
        
        pst.executeUpdate();
        javax.swing.JOptionPane.showMessageDialog(null, "Transaksi Berhasil Disimpan!");
        
        // Refresh tabel transaksi agar data baru langsung muncul di layar
        tampilDataTransaksi();
        
        // Bersihkan semua form inputan setelah berhasil simpan
        txtNotaBooking.setText("");
        cbIdPelanggan.setSelectedIndex(0);
        cbIdLapangan.setSelectedIndex(0);
        txtHargaSewa.setText("");
        txtLamaSewa.setText("");
        txtTotalBayar.setText("");
        
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Gagal menyimpan transaksi: " + e.getMessage());
    }
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanTransaksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }
// Fungsi khusus untuk menarik data dari CMD/MySQL ke JTable visual

    public void tampilDataLapangan() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        model.addColumn("ID Lapangan");
        model.addColumn("Nama Lapangan");
        model.addColumn("Jenis Lapangan");
        model.addColumn("Harga Per Jam");

        try {
            java.sql.Connection conn = Koneksi.koneksiDB();
            String sql = "SELECT * FROM lapangan";
            java.sql.Statement st = conn.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_lapangan"),
                    rs.getString("nama_lapangan"),
                    rs.getString("jenis_lapangan"),
                    rs.getString("harga_perjam")
                });
            }
            tblLapangan.setModel(model);
        } catch (SQLException e) {
            System.out.println("Gagal memuat data ke tabel: " + e.getMessage());
        }
    }
     private void tampilDataPelanggan() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        model.addColumn("ID Pelanggan");
        model.addColumn("Nama Pelanggan");
        model.addColumn("No. Telp");
        model.addColumn("Alamat");

        try {
            java.sql.Connection conn = Koneksi.koneksiDB();
            String sql = "SELECT * FROM pelanggan";
            java.sql.Statement st = conn.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_pelanggan"),
                    rs.getString("nama_pelanggan"),
                    rs.getString("no_telp"),
                    rs.getString("alamat")
                });
            }
            tblPelanggan.setModel(model);
        } catch (SQLException e) {
            System.out.println("Gagal memuat data pelanggan: " + e.getMessage());
}
     }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditLapangan;
    private javax.swing.JButton btnEditPelanggan;
    private javax.swing.JButton btnHapusLapangan;
    private javax.swing.JButton btnHapusPelanggan;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnSimpanLapangan;
    private javax.swing.JButton btnSimpanPelanggan;
    private javax.swing.JButton btnSimpanTransaksi;
    private javax.swing.JComboBox<String> cbIdLapangan;
    private javax.swing.JComboBox<String> cbIdPelanggan;
    private javax.swing.JComboBox<String> cbJenisLapangan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tblLapangan;
    private javax.swing.JTable tblPelanggan;
    private javax.swing.JTable tblTransaksi;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtHargaLapangan;
    private javax.swing.JTextField txtHargaSewa;
    private javax.swing.JTextField txtIdLapangan;
    private javax.swing.JTextField txtIdPelanggan;
    private javax.swing.JTextField txtLamaSewa;
    private javax.swing.JTextField txtNamaLapangan;
    private javax.swing.JTextField txtNamaPelanggan;
    private javax.swing.JTabbedPane txtNoNota;
    private javax.swing.JTextField txtNoTelp;
    private javax.swing.JTextField txtNotaBooking;
    private javax.swing.JTextField txtTotalBayar;
    // End of variables declaration//GEN-END:variables

    public void muatPilihanPelanggan() {
    cbIdPelanggan.removeAllItems();
    cbIdPelanggan.addItem("- Pilih Pelanggan -");
    try {
        java.sql.Connection conn = Koneksi.koneksiDB();
        String sql = "SELECT id_pelanggan FROM pelanggan";
        java.sql.Statement st = conn.createStatement();
        java.sql.ResultSet rs = st.executeQuery(sql);
        while (rs.next()) {
            cbIdPelanggan.addItem(rs.getString("id_pelanggan"));
        }
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Gagal memuat ID Pelanggan: " + e.getMessage());
    }
}

public void muatPilihanLapangan() {
    cbIdLapangan.removeAllItems();
    cbIdLapangan.addItem("- Pilih Lapangan -");
    try {
        java.sql.Connection conn = Koneksi.koneksiDB();
        String sql = "SELECT id_lapangan FROM lapangan";
        java.sql.Statement st = conn.createStatement();
        java.sql.ResultSet rs = st.executeQuery(sql);
        while (rs.next()) {
            cbIdLapangan.addItem(rs.getString("id_lapangan"));
        }
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Gagal memuat ID Lapangan: " + e.getMessage());
    }
}

public void tampilDataTransaksi() {
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
    model.addColumn("No Nota");
    model.addColumn("ID Pelanggan");
    model.addColumn("ID Lapangan");
    model.addColumn("Lama Sewa");
    model.addColumn("Total Bayar");

    try {
        java.sql.Connection conn = Koneksi.koneksiDB();
        String sql = "SELECT * FROM transaksi";
        java.sql.Statement st = conn.createStatement();
        java.sql.ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("no_nota"),
                rs.getString("id_pelanggan"),
                rs.getString("id_lapangan"),
                rs.getInt("lama_sewa") + " Jam",
                rs.getInt("total_bayar")
            });
        }
        tblTransaksi.setModel(model);
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Gagal memuat data transaksi: " + e.getMessage());
    }
}
    }
